### ISSUE TITLE
slush: command not found

### ISSUE THREAD

**Issue by xgz123** [the-simian/slush-phaser-webpack#17]
I run `sudo npm install -g slush-phaser-webpack`
But when I type in _slush_ I got this

**Comment by the-simian** [comment]
hello did you  `npm install -g slush` first? the generator needs the slush cli to run, just like any other library that works similarly (like, say yeoman)

als FYI:, after I finish the videos from my conference in November, I am going to resume heavy work on this project, so expect a lot of major updates.

**Comment by xgz123** [comment]
Hi thanks very much. Yes I didn't install slush. Good job!

**Comment by the-simian** [comment]
ok great, I'll close this then!
