### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by luckylooke** [the-simian/slush-phaser-webpack#2]
Terminal:
WARNING in ./~/phaser/dist/phaser.js
Critical dependencies:
70908:409-416 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/phaser/dist/phaser.js 70908:409-416

ERROR in ./~/phaser/dist/phaser.js
Module not found: Error: Cannot resolve module 'Phaser' in /home/ubuntu/workspace/node_modules/phaser/dist
 @ ./~/phaser/dist/phaser.js 84511:13-30

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: Webpack cannot compile config
    at DestroyableTransform.<anonymous> (/home/ubuntu/workspace/node_modules/gulp-webpack-build/index.js:248:23)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at /home/ubuntu/workspace/node_modules/gulp-webpack-build/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:442:13)

Any hint?

**Comment by luckylooke** [comment]
Build passing when I use this hack: https://github.com/photonstorm/phaser/issues/1186#issuecomment-62481186

**Comment by the-simian** [comment]
@luckylooke thank you very much for submitting the issue!

I'll take a look at this this evening. I got this error on Phaser 2.3.x, but not 2.2.x I made a shim that was working for 2.2.x, I just need to update for 2.3.x

Can you check to see if you're using the latest versions of this scaffold, and Phaser 2.2.x? I plan on updating the shim soon.

Thank you again, for looking into this. I have big plans for this generator, but Its still in development. Sorry if you're hitting kinks right now. 

Latest version should be 0.0.10. I just ran a quick test on my computer and it worked, and also tested on linux (via vm) and mac (on amacbook). It did scaffold the project and boot up, but just so I know what system are you using, etc?

**Comment by luckylooke** [comment]
I cannot check it right now, perhaps tomorrow. But I was trying it today
for the first time so it was very fresh installation. Everything should be
latest then. I was trying to solve the problem or bypass it somehow but
without luck. Hope you will success easily ;-)

**Comment by the-simian** [comment]
Hey just to help you out I ran the scaffold and pushed the output to a repo:

[Phaser Webpack Example](https://github.com/the-simian/phaser-webpack-output-example)

It currently is working with no build errors. All I get are warnings - "prebuilt files", but otherwise works.

After running the scaffold (the npm installs automatically here, but you'll need to do `npm install` yourself)

I then do `gulp build` - build into `dist` folder

`node server`

and then I get this

![http://i.imgur.com/51EfhXh.png](http://i.imgur.com/51EfhXh.png)

you might try pulling that one down and seeing if it looks the same as yours. Make sure its pointing to all the shims and stuff.

Again, thanks for your time in this matter - all your attention helps me build something we can both use!

**Comment by luckylooke** [comment]
Thank you. I will look at it this week and let you know ;-)

**Comment by luckylooke** [comment]
Same error :/
ERROR in ./~/phaser/dist/phaser.js
Module not found: Error: Cannot resolve module 'Phaser' in /home/ubuntu/workspace/node_modules/phaser/dist
 @ ./~/phaser/dist/phaser.js 84511:13-30

I was checking phaser version and it is version 2.2.2

**Comment by the-simian** [comment]
Did you get that error in the spit out example project also?

**Comment by luckylooke** [comment]
Yes

**Comment by the-simian** [comment]
Ok it seems like its working on windws and osx, but not ubuntu... for some reason.I'll test it again in a VM, sorry about your troubles. If you solve it before I do- submit a PR, I'd very much appreciate it

**Comment by the-simian** [comment]
@luckylooke I have completely updated the build process, and also updated phaser to the next version.

Think you can give it another shot?

**Comment by the-simian** [comment]
@luckylooke I found a minor error that was reported in another issue #7  , so be aware it might fail build until that is fixed. I haven't looked into it just yet.

references #7

**Comment by luckylooke** [comment]
Hi, @the-simian 
There were some errors while install (slush phaser-webpack):

```
npm ERR! peerinvalid The package phaser does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer phaser-shim-loader@0.0.3 wants phaser@2.2.x

npm ERR! System Linux 3.14.13-c9
npm ERR! command "/home/ubuntu/.nvm/v0.10.35/bin/node" "/home/ubuntu/.nvm/v0.10.35/bin/npm" "install"
npm ERR! cwd /home/ubuntu/workspace
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code EPEERINVALID
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/ubuntu/workspace/npm-debug.log
npm ERR! not ok code 0
[19:21:30] npm exited with non-zero code 1 , run `npm install` manually

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: npm exited with non-zero code 1
    at ChildProcess.<anonymous> (/home/ubuntu/.nvm/v0.10.35/lib/node_modules/slush-phaser-webpack/node_modules/gulp-install/lib/commandRunner.js:14:19)
    at ChildProcess.emit (events.js:98:17)
    at maybeClose (child_process.js:766:16)
    at Process.ChildProcess._handle.onexit (child_process.js:833:5)
```

after it gulp build throws some warnings:

```
WARNING in ./~/phaser/dist/phaser.js
Critical dependencies:
64791:385-392 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/phaser/dist/phaser.js 64791:385-392

WARNING in ./~/phaser/dist/phaser.js
Module not found: Error: Cannot resolve module 'nw.gui' in /home/ubuntu/workspace/node_modules/phaser/dist
 @ ./~/phaser/dist/phaser.js 43737:44-61
```

But example app starts and looks like your screenshot, only reports some warnings to console:

```
WebGL: INVALID_VALUE: vertexAttribPointer: index out of range
17pixi.dev.js:10438 WebGL: INVALID_VALUE: vertexAttribPointer: index out of range
pixi.dev.js:10438 WebGL: INVALID_VALUE: vertexAttribPointer: index out of range
237pixi.dev.js:10438 WebGL: INVALID_VALUE: vertexAttribPointer: index out of range
pixi.dev.js:10438 WebGL: too many errors, no more errors will be reported to the console for this context.
```

But they seems not to be related to issue :)

When I sattisfy phaser-shim-loader needs by changing phaser 2.3.x to 2.2.x in package.json, it didnt throw error during installation but example app is not working and throws into console this: Uncaught ReferenceError: Phaser is not defined

Thats wierd :D

**Comment by the-simian** [comment]
Hey I think I took the `phaser-shim-loader` out entirely - the latest version shouldn't be using that, the process is totally different right now. I made a comment about it on the thread you linked earlier : https://github.com/photonstorm/phaser/issues/1186#issuecomment-104306080

try to uninstall slush-phaser-webpack, clear your npm cache (`npm cache clean`) and then reinstall the latest version. Your peer-dependency error shouldn't be present in the latest version of the generator.

You can see here https://github.com/the-simian/slush-phaser-webpack/blob/master/templates/default/package.json that the shim isn't even included at all in the latest template.

**Comment by the-simian** [comment]
@luckylooke OK, there's yet another new version. If you try again, do a full reinstall.

**Comment by luckylooke** [comment]
Installation with no errors, but gulp task build have problem:

```
gulp build

Error: Cannot find module './build/scripts'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/ubuntu/workspace/gulp/build.js:4:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by luckylooke** [comment]
I have copied folder "build" from https://github.com/the-simian/phaser-webpack-output-example and it works as expected. Maybe you throw it from your generator package accidentally.

Warnings are still present

```
WARNING in ./~/phaser/dist/phaser.js
Critical dependencies:
64791:385-392 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/phaser/dist/phaser.js 64791:385-392

WARNING in ./~/phaser/dist/phaser.js
Module not found: Error: Cannot resolve module 'nw.gui' in /home/ubuntu/workspace/node_modules/phaser/dist
 @ ./~/phaser/dist/phaser.js 43737:44-61
```

There is multiple possibilities how include third party libraries in webpack project, but I am just beginner with it and I haven't found example which works for Phaser not to throwing those warnings.

**Comment by the-simian** [comment]
Getting the warnings is normal. Webpack doesn't like 'prebuilt' looking files. This isn't a big deal, its just a warning. As of my last comment, I added the build folders back to this project on the scaffold. The templated project's .gitignore was causing them to get excluded in the parent generator. 

Since you're getting a build, I'm gonna go ahead and close this. If you encounter anything else, just open an issue and I'll make sure to fix it. I don't think the warnings will affect your game. Keep an eye on the repo too, I'll be actively adding more capabilities to the scaffold.
